#!/usr/bin/perl
use vars qw'$DB::inhibit_exit';
$DB::inhibit_exit = 0;

use strict;

use File::Basename;
use File::Slurp qw{read_file};

my $infile = shift;
my @libs = ();
unshift @libs, '-l', 'linux' if $infile ne 'linux.lua';
my @toexec = ('/usr/bin/lua', @libs, $infile);
# warn "+ @toexec\n";
exec @toexec;
