#!/usr/bin/perl
use vars qw'$DB::inhibit_exit';
$DB::inhibit_exit = 0;

use strict;

use File::Basename;
use File::Slurp qw{read_file};

my $infile = shift;
my @libs = ();
my $infiledir = dirname $infile;
for my $d (glob 'libs/*') {
    my $b = basename($d);
    next if $d eq $infiledir or $b eq 'LibAddonMenu-2';
    my $p = $d . '/' . basename($d);
    if ($b eq 'LibStub' || $b eq 'LibMapPing') {
        unshift @libs, '-l', $p;
    } else {
        push @libs, '-l', $p;
    }
}

unshift @libs, '-l', 'linux';

my @toexec = ('/usr/bin/lua', @libs, $infile);
warn "+ @toexec\n";
exec @toexec;
