#!/usr/bin/perl
use vars qw'$DB::inhibit_exit';
$DB::inhibit_exit = 0;

use strict;

use File::Basename;
use File::Slurp qw{read_file};

my %seen = map {$_ => 1} @ARGV;
@ARGV = grep {$seen{$_}--} @ARGV;

unshift @ARGV, '-l', 'linux' if " @ARGV " !~ / linux\.lua /o;
my @toexec = ('/usr/bin/lua', @ARGV);
# warn "+ @toexec\n";
exec @toexec;
