#!/bin/sh -e
cd ..
files=$({ echo POC/POC.lua; sed -nr -e '/^( *$|#|;)/d' -e 's%^%POC/%p' POC/POC.txt; } | sort)
ver=$(/bin/sed -nre "s/^[local      ]*version[      ]*=[    ]*['\"](.*)['\"]/\1/p" POC/POC.lua)
rm -f POC-$ver.zip
echo creating /tmp/POC-$ver.zip
exec zip /tmp/POC-$ver.zip POC $files
