#!/bin/sh
cd ..
files=$({ echo POC/POC.txt; sed -nr -e '/^( *$|#|;)/d' -e 's%^%POC/%p' POC/POC.txt; } | sort)
ver=$(awk '/^## *Version:/{print $3}' POC/POC.txt)
rm -f POC-$ver.zip
echo creating /tmp/POC-$ver.zip
exec zip /tmp/POC-$ver.zip POC $files
