#!/bin/sh -e
here=$(pwd)
mkdir /tmp/$$
ln -s $here /tmp/$$/POC
cd /tmp/$$
files=$({ echo POC/POC.txt; sed -nr -e '/^( *$|#|;)/d' -e 's%^%POC/%p' POC/POC.txt; } | sort)
if [ -n "$1" ]; then
    ver=$1
else
    ver=$(/bin/sed -nre "s/^[local      ]*version[      ]*=[    ]*['\"](.*)['\"]/\1/p" POC/POC.lua)
fi
rm -f /tmp/POC-$ver.zip
zip /tmp/POC-$ver.zip POC $files
echo "
created /tmp/POC-$ver.zip"
cd /tmp
exec /bin/rm -rf /tmp/$$
